theme: minima
title: Stock Utilities Blog
description: "Your go-to resource for insightful stock market analyses, tips, and trends!"
google_analytics: UA-XXXXXX-X

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  social_links:
    - platform: twitter
      user_url: "https://twitter.com/stock_utilities"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
header_pages:
  - index.html
  - about.md
